question_data= [
    {"question": "Python is a low-level programming language.", "answer": False},
    {"question": "Water boils at 100 degrees Celsius at sea level.", "answer": True},
    {"question": "The capital of Australia is Sydney.", "answer": False},
    {"question": "Light travels faster than sound.", "answer": True},
    {"question": "Humans have three lungs.", "answer": False},
    {"question": "The Great Wall of China is visible from space.", "answer": False},
    {"question": "The chemical symbol for Gold is 'Au'.", "answer": True},
    {"question": "The square root of 64 is 6.", "answer": False},
    {"question": "The Pacific Ocean is the largest ocean on Earth.", "answer": True},
    {"question": "Sharks are mammals.", "answer": False},
    {"question": "The human body has four lungs.", "answer": False},
    {"question": "The currency of Japan is the Yen.", "answer": True},
    {"question": "Plants produce oxygen during photosynthesis.", "answer": True},
    {"question": "A leap year has 366 days.", "answer": True},
    {"question": "The freezing point of water is 0 degrees Fahrenheit.", "answer": False},
    {"question": "The moon is a star.", "answer": False},
    {"question": "Bats are blind.", "answer": False},
    {"question": "Lightning never strikes the same place twice.", "answer": False},
    {"question": "The Great Pyramid of Giza is in Egypt.", "answer": True},
    {"question": "Venus is the hottest planet in our solar system.", "answer": True},
    {"question": "Sound can travel through a vacuum.", "answer": False},
    {"question": "The human skeleton has over 200 bones.", "answer": True},
    {"question": "The capital of Canada is Toronto.", "answer": False},
    {"question": "Octopuses have three hearts.", "answer": True},
    {"question": "Bananas grow on trees.", "answer": False},  # Technically a large herb
    {"question": "Albert Einstein developed the theory of relativity.", "answer": True},
    {"question": "The Sun is a planet.", "answer": False},
    {"question": "An ostrich can fly.", "answer": False},
    {"question": "The Eiffel Tower is located in Berlin.", "answer": False},
    {"question": "Penguins live in the Arctic.", "answer": False},
    {"question": "The Amazon Rainforest is the largest tropical rainforest in the world.", "answer": True},
    {"question": "There are 50 states in the United States.", "answer": True},
    {"question": "A group of lions is called a pride.", "answer": True},
    {"question": "Electrons are larger than atoms.", "answer": False},
    {"question": "Mount Everest is the tallest mountain in the world.", "answer": True},
    {"question": "All spiders have eight legs.", "answer": True},
    {"question": "Chocolate is toxic to dogs.", "answer": True},
    {"question": "The longest river in the world is the Amazon River.", "answer": False},  # Nile is usually considered longer
    {"question": "A triangle has four sides.", "answer": False},
    {"question": "Whales are fish.", "answer": False},
    {"question": "Humans can breathe in space without a spacesuit.", "answer": False},
    {"question": "Jupiter is the largest planet in our solar system.", "answer": True},
    {"question": "The heart is a muscle.", "answer": True},
    {"question": "Pluto is still classified as a planet.", "answer": False},
    {"question": "Glass is a solid.", "answer": False},  # Technically it's an amorphous solid
    {"question": "Birds are cold-blooded animals.", "answer": False},
    {"question": "The Atlantic Ocean is bigger than the Indian Ocean.", "answer": True},
    {"question": "Bamboo is the fastest growing plant.", "answer": True},
    {"question": "The Earth revolves around the Sun.", "answer": True},
    {"question": "You can see ultraviolet light with the naked eye.", "answer": False}
]
